# Generated by Django 3.2.5 on 2021-07-06 14:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Tec', models.CharField(max_length=30)),
                ('link_Tec', models.CharField(max_length=100)),
                ('descr_Tec', models.CharField(max_length=255)),
                ('tags_Tec', models.CharField(max_length=255)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
